DROP TABLE ap_user CASCADE;
DROP TABLE map CASCADE;
DROP TABLE map_data CASCADE;
DROP TABLE map_thumbnail CASCADE;
DROP TABLE map_permission CASCADE;
DROP TABLE tag CASCADE;
DROP TABLE tag_implies CASCADE;
DROP TABLE map_tag CASCADE;
