name: dev_accel_pen

secrets:
  db_password:
    file: ${ACCEL_PEN_DB_PASSWORD_PATH}

volumes:
  database:

services:
  database:
    image: postgres:17.4-bookworm
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: accel_pen
    ports:
      - "5432:5432"
