name: dev_accel_pen

secrets:
  db_root_password:
    file: ${ACCEL_PEN_DB_PASSWORD_PATH}

volumes:
  database:

services:
  database:
    build:
      context: ./backend
      dockerfile: database.Dockerfile
    restart: always
    volumes:
      - database:/var/lib/mysql
    secrets:
      - db_root_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: accel_pen
    ports:
      - "3306:3306"
