name: accel_pen

secrets:
  db_password:
    file: ${ACCEL_PEN_DB_PASSWORD_PATH}
  nadeo_client_secret:
    file: ${ACCEL_PEN_NADEO_AUTH_SECRET_PATH}
  ubi_password:
    file: ${ACCEL_PEN_NADEO_UBI_PASSWORD_PATH}

volumes:
  database:

services:
  backend:
    build:
      context: .
    restart: always
    depends_on:
      - database
    ports:
      - "2460:2460"
    secrets:
      - db_password
      - nadeo_client_secret
      - ubi_password
    environment:
      ACCEL_PEN_DB_PASSWORD_PATH: /run/secrets/db_password
      ACCEL_PEN_NADEO_AUTH_SECRET_PATH: /run/secrets/nadeo_client_secret
      ACCEL_PEN_NADEO_UBI_PASSWORD_PATH: /run/secrets/ubi_password

  database:
    image: postgres:17.4-bookworm
    volumes:
      - database:/var/lib/mysql
    secrets:
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: accel_pen
