// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapDataResponse } from "./MapDataResponse";

export type AllMapsByResponse = { "type": "AllMapsByResponse", maps: Array<MapDataResponse>, };
