// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorInner = "Database" | "Migration" | "InvalidMapDataRequest" | "UrlParseError" | "SessionError" | "AxumError" | "NadeoApiFailed" | "OauthFailed" | "InvalidOauth" | "MapNotFound" | "NotFound";
