// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiErrorInner = "Database" | "Migration" | "InvalidQuery" | "UrlParseError" | "SessionError" | "AxumError" | "ApiFailed" | "ApiReturnedError" | "InvalidJson" | "InvalidOauth" | "UnexpectedResponse" | "Rejected" | "MapNotFound" | "MultipartError" | "InvalidMultipart" | "MissingFromMultipart" | "InvalidGbx" | "NotAMap" | "NotYourMap" | "NotBase64" | "NotUtf8" | "NotUuid" | "NotFound";
