// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthorResponse = { "type": "AuthorResponse", account_id: string, display_name: string, club_tag: string, };
