// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserResponse } from "./UserResponse";

export type FavoriteMapResponse = { "type": "FavoriteMapResponse", uid: string, name: string, author: UserResponse, };
