// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserOrAuthor } from "./UserOrAuthor";

export type FavoriteMapResponse = { "type": "FavoriteMapResponse", uid: string, name: string, author: UserOrAuthor, };
