// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OauthResponse = { "type": "OauthResponse", access_token: string, refresh_token: string, };
