// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SelfResponse = { "type": "SelfResponse", display_name: string, account_id: string, club_tag: string, };
