// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthorResponse } from "./AuthorResponse";
import type { UserResponse } from "./UserResponse";

export type UserOrAuthor = { "User": UserResponse } | { "Author": AuthorResponse };
