//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "map_data")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub row_id: i32,
    pub ap_map_id: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub gbx_data: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::map::Entity",
        from = "Column::ApMapId",
        to = "super::map::Column::ApMapId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Map,
}

impl Related<super::map::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Map.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
