//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub tag_id: i32,
    #[sea_orm(column_type = "Text")]
    pub tag_name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub tag_definition: Option<String>,
    pub implication: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::map_tag::Entity")]
    MapTag,
}

impl Related<super::map_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MapTag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
