//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tag_implies")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub dummy: i32,
    pub implication: i32,
    pub implyer: i32,
    pub implied: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::Implied",
        to = "super::tag::Column::TagId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tag2,
    #[sea_orm(
        belongs_to = "super::tag::Entity",
        from = "Column::Implyer",
        to = "super::tag::Column::TagId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Tag1,
}

impl ActiveModelBehavior for ActiveModel {}
