INSERT INTO tag (tag_name, tag_kind) VALUES
    ('FullSpeed',         'mapStyle'),
    ('SpeedFun',          'mapStyle'),
    ('Tech',              'mapStyle'),
    ('SpeedTech',         'mapStyle'),
    ('RPG',               'mapStyle'),
    ('MiniRPG',           'mapStyle'),
    ('LOL',               'mapStyle'),
    ('Trial',             'mapStyle'),
    ('ZrT',               'mapStyle'),
    ('Competitive',       'mapStyle'),
    ('Kacky',             'mapStyle'),
    ('Endurance',         'mapStyle'),
    ('Obstacle',          'mapStyle'),
    ('Nascar',            'mapStyle'),
    ('Transitional',      'mapStyle'),
    ('Backwards',         'mapStyle'),
    ('Pathfinding',       'mapStyle'),

    ('Mixed',             'definingSurface'),
    ('Offroad',           'definingSurface'),
    ('Underwater',        'definingSurface'),
    ('Turtle',            'definingSurface'),
    ('Ice',               'definingSurface'),
    ('Bobsleigh',         'definingSurface'),
    ('WetWood',           'definingSurface'),
    ('WetIcyWood',        'definingSurface'),
    ('Dirt',              'definingSurface'),
    ('Plastic',           'definingSurface'),
    ('Grass',             'definingSurface'),
    ('Wood',              'definingSurface'),

    ('NoBrakes',          'mapFeature'),
    ('Reactor',           'mapFeature'),
    ('SlowMotion',        'mapFeature'),
    ('Fragile',           'mapFeature'),
    ('EngineOff',         'mapFeature'),
    ('CruiseControl',     'mapFeature'),
    ('NoSteering',        'mapFeature'),
    ('NoGrip',            'mapFeature'),
    ('Water',             'mapFeature'),
    ('Sausage',           'mapFeature'),
    ('Magnet',            'mapFeature'),
    ('Bumper',            'mapFeature'),
    ('MovingItems',       'mapFeature'),
    ('Pipes',             'mapFeature'),

    ('Bugslide',          'drivingTechnique'),
    ('Mudslide',          'drivingTechnique'),
    ('Gear3',             'drivingTechnique'),
    ('Gear4',             'drivingTechnique'),

    ('SnowCar',           'notStadium'),
    ('DesertCar',         'notStadium'),
    ('RallyCar',          'notStadium'),
    ('MixedCar',          'notStadium'),

    ('AlteredNadeo',      'mapMeta'),
    ('Mini',              'mapMeta'),
    ('SecretLeaderboard', 'mapMeta'),
    ('Scenery',           'mapMeta'),
    ('Signature',         'mapMeta'),
    ('Educational',       'mapMeta'),
    ('SpeedMapping',      'mapMeta'),
    ('PressForward',      'mapMeta'),
    ('Race',              'mapMeta'),
    ('Stunt',             'mapMeta'),
    ('Platform',          'mapMeta'),
    ('Royal',             'mapMeta'),
    ('Puzzle',            'mapMeta')
;

