// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Format } from "./Format";

export type FormattedChar = { char: string, icon: boolean, color: Color | null, format: Array<Format>, };
