// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormattedString } from "./FormattedString";
import type { Medals } from "./Medals";
import type { TagInfo } from "./TagInfo";
import type { UserResponse } from "./UserResponse";

export type MapContext = { id: number, gbx_uid: string, plain_name: string, name: FormattedString, votes: number, uploaded: string, created: string, author: UserResponse, tags: Array<TagInfo>, medals: Medals | null, };
