// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserResponse } from "./UserResponse";

export type MapDataResponse = { "type": "MapDataResponse", name: string, author: UserResponse, uploaded: string, map_id: number, uid: string, };
