// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapManageCommand } from "./MapManageCommand";

export type MapManageRequest = { "type": "MapManageRequest", command: MapManageCommand, };
