// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { TagInfo } from "./TagInfo";

export type MapManageCommand = { "type": "SetTags", tags: Array<TagInfo>, } | { "type": "SetPermissions", permissions: Array<Permission>, } | { "type": "Delete" };
