// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagInfo } from "./TagInfo";

export type MapSearchRequest = { tagged_with: TagInfo | null, };
