// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MapContext } from "./MapContext";
import type { UserResponse } from "./UserResponse";

export type MapUsers = { "type": "MapUsers", map: MapContext, users: Array<UserResponse>, };
