// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Permission = { "type": "Permission", user_id: number, display_name: string, may_manage: boolean, may_grant: boolean, };
