// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission } from "./Permission";
import type { PermissionUpdateType } from "./PermissionUpdateType";

export type PermissionUpdate = { "type": "PermissionUpdate", permission: Permission, update_type: PermissionUpdateType, };
