// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserResponse = { "type": "UserResponse", display_name: string, account_id: string, user_id: number, club_tag: string | null, };
